### ISSUE TITLE
Remove-PreviousOfficeInstalls Script Doesn't work with Office 2013

### ISSUE THREAD

**Issue by csmallmda** [OfficeDev/Office-IT-Pro-Deployment-Scripts#117]
Running the Remove-PreviousOfficeInstalls doesn't appear to work with Office 2013.

Get-OfficeVersion seems to return the correct installed version of 2013 but doesn't seem to call the VBS script for removal. The script doesn't do anything as far as removing the installed version of Office 2013.

The script works fine with Office 2010.

**Comment by csmallmda** [comment]
I tried the latest edits again against 2013 and still no luck. You execute the script and it does absolutely nothing. If I manually launch the Get-OfficeVersion function, it returns the correct installed version of 2013. If I then also manually launch the Remove-PreviousOfficeInstalls function, it removes Office 2013.

The script seems to be broken with respect to 2013 installations. When this same script is run against a 2010 installation, it works as expected.

**Comment by v-rusmit** [comment]
Thank you for your feedback.  We will look into the issue.

**Comment by v-rusmit** [comment]
We have made some changes to the script that we hope will fix the issues you experienced. Please let us know if the latest version works.

**Comment by vercetti757** [comment]
Hi v-rusmit,

Thank you for looking into this issue. I am also running into the same issue as csmallmda even with the most recent version posted yesterday. I dot-sourced the Remove-PreviousOfficeInstalls.ps1 script into my PS Session, when I run "Get-OfficeVersion -ShowAllInstalledProducts" it detects C2R "Microsoft Office 365 - en-us 15.0.4841.1001" installed.

When I run "Remove-PreviousOfficeInstalls" the console reads:

Detecting Office installs...
Microsoft Office is not installed

It seems that OffScrubC2R.vbs is not being called because the Remove-PreviousOfficeInstalls function is not properly detecting Click to Run versions of Office 365 products. I have the same issue with Office 2016 Click to Run products not being uninstalled as well.

I tried various flags in different combinations such as:

"Remove-PreviousOfficeInstalls -RemoveClickToRunVersions 1 -R
emove2016Installs 1 -Force 1"

But it does not seem to detect or uninstall any of the Click to Run variants of Office.

Thank you again for looking into this and hope to get the removal part working for this excellent set of deployment scripts.

**Comment by csmallmda** [comment]
v-rusmit,

It is also worth mentioning that I am using these scripts to deploy via SCCM. Previously, the script to remove previous installs opened a command prompt window on the client when the vbs script was called.

I am very happy to say that the revised scripts not only remove 2013 now but also do not have the command prompt window that pops up. I used to have to kill that cmd.exe process to make my installation script proceed but now it no longer pops up so I am happy about that!

Thanks!
