### ISSUE TITLE
Using your install generator to make a office 2013 installer?

### ISSUE THREAD

**Issue by Slackerony** [OfficeDev/Office-IT-Pro-Deployment-Scripts#156]
Hi

I've used your install generator to make a silent office2016 executable installer, and it worked like a charm!
However, I'd like to also make one for Office2013, and i can't seem to figure out whether or not this is possible, as the configuration.xml files seems to be identical, no matter what you do.

Any helps appreciated!

**Comment by davguent** [comment]
It doesn't appear possible.  Likely because Office 2013 (C2R) is end of life in February.  "You can continue to receive updates for the Office 2013 version of Office 365 ProPlus until February 2017. After February 2017, there will be no more updates for Office 2013. Therefore, we recommend that you update to the Office 2016 version of Office 365 ProPlus as soon as possible."   At this point, best to halt 2013 deployment where possible.  https://support.microsoft.com/en-us/kb/3097292

**Comment by johnskydiver** [comment]
Thank you for your feedback.  As @davguent stated, Office 2013 is being phased out, we do not plan on making the toolkit backward compatible with Office 2013.  I'm glad to hear that the toolkit works well for you using Office 2016, and would like to state that if you wish to deploy Office 2013 silently, we have powershell scripts that will do silent installs that can be set to use Office 2013, or you can use the Office 2013 ODT, just remember in the ODT to set the display property to none, and that will force a silent install.  Thank you for your time.
