### ISSUE TITLE
MSI Creation not embedding files correctly

### ISSUE THREAD

**Issue by keane2017** [OfficeDev/Office-IT-Pro-Deployment-Scripts#182]
Good morning
created an officeproplus.msi fine last night with the files embedded as you can see in the picture below the size is correct.

today I have selected only visio and to embed the files but the MSI is not correctly generating
please see below the visioproplus.msi is only small with the office folder separate?

![msiissue2](https://cloud.githubusercontent.com/assets/23102516/19966818/5eab4a8e-a1c5-11e6-8ab8-e3a15a17f3e5.JPG)

![msiissue1](https://cloud.githubusercontent.com/assets/23102516/19966801/4e55f300-a1c5-11e6-95cc-c24902e34e78.JPG)

The office folder is being output separately from the MSI, can you advise why this behaviour has changed please?

Thanks

**Comment by johnskydiver** [comment]
@keane2017 This behavior is working as designed.  If the contents of the files to be imbedded exceed 2GB, they are pushed into a folder that is to be kept in the same directory as the MSI during deployment.  The issue is that the generated files are only 32 bit, and any file size generated over 2GB will crash and fail.

**Comment by keane2017** [comment]
Hi
I am only selecting Visio?
I have created 3 or 4 this week that have all worked ok?
I'm not sure what you mean? it wasn't working like this the other day?
Thanks

**Comment by johnskydiver** [comment]
if you notice, a new version was deployed overnight it looks like, 16.0.7369.2038.  The contents of this folder are larger than the contents of the prior version.  embedding these files will cause the msi to meet or exceed the file size limitations of a 32 bit file for Microsoft Windows, so instead of creating a file too large for a 32 bit windows application, we copy the files to the "office" folder that you see created in the same directory as your generated MSI.  This is to prevent the application from crashing when launched.  Just make sure that "office" folder is kept in the same folder as the MSI when you launch it on a client machine.  The MSI will copy the contents to the correct location on the client when it's run.  If you're still uncertain about why this there is a file size limitation, I suggest performing a google search with the key terms "32 bit file size limit", this will explain to you the issues we were running into when we were first writing and deploying this toolkit.  Thanks.

**Comment by keane2017** [comment]
Hi
I understand the limits
My point was it's not over the threshold like you say it's the same size as the officeproplus msi I have. 
Thanks for letting me know though I don't think the limit is the issue here.

Thanks for your help

**Comment by johnskydiver** [comment]
It's no problem.  It may not be over the limit, but if it's close enough to be questionable, then the cut off is made, and we put the source files in another folder just to be on the safe side.

**Comment by keane2017** [comment]
Makes sense :)
Thanks for the quick responses it's appreciated

**Comment by keane2017** [comment]
Does the msi work differently when compiled like this?
The source files don't appear in the temp folder as before when they are separate to the msi?
Only the setup and config files do?

**Comment by johnskydiver** [comment]
Thank you for pointing out this issue, I will work on fixing it.  In the meantime, I suggest you use MSI without embedding the files, or use the exe option if you plan on embedding.

**Comment by keane2017** [comment]
The exe was doing the same.

I have deployed both fine today but wasn't sure where the files were ?

It must be picking up from the internet?

I'll await the fix to ensure it's deploying properly.

Thanks

**Comment by keane2017** [comment]
Hi
is there any update on this please?
Thanks

**Comment by johnskydiver** [comment]
Issue has been resolved today.  thanks
