### ISSUE TITLE
MSI generation broken?

### ISSUE THREAD

**Issue by dzsoda** [OfficeDev/Office-IT-Pro-Deployment-Scripts#190]
It seems like the MSI generation function in the Office365 ProPlus Install Toolkit is broken. It could be just my fault but I tried it on different workstations with different OSes (Win10 and Win81 Pro) and all I get is a .wxs file at the end as an output. A few months ago, it worked perfectly fine.
Executable (.exe) generation seems to be OK though.

**Comment by johnskydiver** [comment]
@dzsoda The Install Toolkit is functioning just fine.  If you're having issues it may be due to the install toolkit not installing on your client correctly, please uninstall the toolkit, and re-download and install it and try again.  Also make sure that whichever client you are using to create the MSI file from the install toolkit is operating with at least .net 4.5 framework.  Thanks.
