### ISSUE TITLE
fa-ir is missing in Download-OfficeProPlusChannels.ps1

### ISSUE THREAD

**Issue by netraser** [OfficeDev/Office-IT-Pro-Deployment-Scripts#195]
The Language Code fa-ir is missing in the line 92

**Comment by netraser** [comment]
and also in Edit-OfficeConfigurationFile.ps1
Line 125 add 

,"Farsi|fa-ir"

**Comment by AStigall** [comment]
@netraser we have been discussing this issue for the past couple of weeks. Do you install it as the primary language or do you need to specify a different language first?

We'd love to hear your feedback on this. There are several other languages that fall under this category, and if we need to add them as available core languages we can consider that, but we're hesitant to do that since they don't have all of the necessary components of a core language pack.

**Comment by netraser** [comment]
I've changed this for my customer in the script by myself. It is not urgent. The best would be if the languages could be fully dynamically. So, if you / Microsoft add an additional language no script change would be needed. I’m not sure if this is possible and the language list could be obtained from the CDN.

**Comment by johnskydiver** [comment]
@netraser The scripts have been updated to include partial and proofing languages.  These languages can be added using the parameters PartialLanguages and ProofingLanguages
