### ISSUE TITLE
"Sourcepath" doesn't get included

### ISSUE THREAD

**Issue by Dviros** [OfficeDev/Office-IT-Pro-Deployment-Scripts#245]
HI!
While using the tool, I was possible to generate the configuration.xml file.
However, this file did not include a very important part - SourcePath. I had to manually add it.
I've pointed it out when using the tool, and generated an installation file with no embedded installation files.
Can you please verify?
Thanks,
Dvir

**Comment by alex182** [comment]
@Dviros  which tool are you talking about?  [The XML Editor](https://officedev.github.io/Office-IT-Pro-Deployment-Scripts/XmlEditor.html)?

**Comment by Dviros** [comment]
Hey @alex182, it's the "Microsoft Office ProPlus Install Toolkit"

**Comment by AStigall** [comment]
@Dviros We've tested the most recent version of the Toolkit and it adds the SourcePath if you specify it. If you don't specify a SourcePath and choose to embed the files, the operation will still work because the ODT will look in the current directory for the source files. These files get extracted to C:\Windows\Temp\OfficeProPlus.
